
NAME = "name"
SOURCE = "source"
# was the source file generated by us as well?
IS_SOURCE_GENERATED = "is_source_generated"
# simple string replacement
REPLACE = "replace"
# Replacements within the specified keycode
KEYCODE_REPLACE = "keycode_replace"
# remove "map key scancode KEYCODE" by scancode
REMOVE_SCANCODES = "remove_scancodes"
# remove "key KEYCODE { ... } " by KEYCODE
REMOVE_KEYCODES = "remove_keycodes"
ADD = "add"

# complex replacement
# replace only within keycode
REPL_KEYCODE = "repl_keycode"
# prev string
REPL_OLD = "repl_old"
# replacement string
REPL_NEW = "repl_new"
# do not replace if line contains:
REPL_SKIP = "repl_skip"

FN = "$fn"
SHIFT = "$shift"
RALT = "$ralt"
LALT = "$lalt"
BASE = "$base"
