
from consts import *

# Maps FxTec Pro1 scan codes to Android key codes.
# See: https://developer.android.com/reference/android/view/KeyEvent
QWERTZ_SCAN_CODES = [
    # ROW 1
    ("$key-1$","ESCAPE"),
    ("$key-2$","1"),
    ("$key-3$","2"),
    ("$key-4$","3"),
    ("$key-5$","4"),
    ("$key-6$","5"),
    ("$key-7$","6"),
    ("$key-8$","7"),
    ("$key-9$","8"),
    ("$key-10$","9"),
    ("$key-11$","0"),
    ("$key-12$","MINUS"),
    ("$key-13$","EQUALS"),
    ("$key-14$","DEL"),
    # ROW 2
    ("$key-15$","TAB"),
    ("$key-41$","Q"),
    ("$key-16$","W"),
    ("$key-17$","E"),
    ("$key-18$","R"),
    ("$key-19$","T"),
    ("$key-20$","Z"),
    ("$key-21$","U"),
    ("$key-22$","I"),
    ("$key-23$","O"),
    ("$key-24$","P"),
    ("$key-25$","GRAVE"),
    ("$key-39$","SEMICOLON"),
    ("$key-111$","FORWARD_DEL"),
    # ROW 3
    ("$key-58$","CAPS_LOCK"),
    ("$key-43$","A"),
    ("$key-30$","S"),
    ("$key-31$","D"),
    ("$key-32$","F"),
    ("$key-33$","G"),
    ("$key-34$","H"),
    ("$key-35$","J"),
    ("$key-36$","K"),
    ("$key-37$","L"),
    ("$key-38$","BACKSLASH"),
    ("$key-40$","APOSTROPHE"),
    ("$key-28$","ENTER"),
    # ROW 4
    ("$key-54$","SHIFT_RIGHT"),
    ("$key-26$","LEFT_BRACKET"),
    ("$key-27$","Y"),
    ("$key-44$","X"),
    ("$key-45$","C"),
    ("$key-46$","V"),
    ("$key-47$","B"),
    ("$key-48$","N"),
    ("$key-49$","M"),
    ("$key-50$","COMMA"),
    ("$key-51$","PERIOD"),
    ("$key-52$","RIGHT_BRACKET"),
    ("$key-103$","DPAD_UP"),
    # ROW 5
    ("$key-29$","CTRL_LEFT"),
    ("$key-464$","FUNCTION"),
    ("$key-172$","ALT_RIGHT"), # Fx
    ("$key-56$","ALT_LEFT"),
    ("$key-249$","ASSIST"),
    ("$key-57$","SPACE"),
    ("$key-105$","DPAD_LEFT"),
    ("$key-108$","DPAD_DOWN"),
    ("$key-106$","DPAD_RIGHT"),
]
